package com.sgu.tuyensinh.admin.ui;

import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import org.springframework.stereotype.Component;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 * @author QUAN
 */
@Component
public class MainFrame extends JFrame {
    // Panel
//    private SanPham sanphamPanel;
//    private NhaCungCap nhacungcapPanel;
//    private KhachHang khachHangPanel;
//    private NhanVien nhanVienPanel;
//    private ThuocTinh thuocTinhPanel;
//    private PhieuNhap phieuNhapPanel;
//    private HoaDon hoaDonPanel;
//    private ThongKe thongKePanel;
//    private NhomQuyen nhomQuyenPanel;
//    private final NhanVienDTO nhanVien; // lưu lại nhân viên đăng nhập

    /**
     * Creates new form Main
     *
     *
     */
    public MainFrame() {
//        this.nhanVien = nhanVien;
        // Setup Frame Attributes
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setTitle("Hệ thống quản lý tuyển sinh đại học");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        // Init Frame's Components 
        setUT();
        initComponents();
        addIconTaskbar();

        // Gán tên và chức vụ
        lblTenAdmin.setText("Quản trị viên");
        lblChucVu.setText("Admin");

//        phanQuyenTheoVaiTro();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuTaskbar = new javax.swing.JPanel();
        info = new javax.swing.JPanel();
        lblTenAdmin = new javax.swing.JLabel();
        bar = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        taskBar = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JToggleButton("<html>&nbsp;&nbsp;&nbsp;Trang chủ</html>");
        btnNganh = new javax.swing.JToggleButton();
        btnToHopMon = new javax.swing.JToggleButton();
        btnThiSinh = new javax.swing.JToggleButton();
        btnBangQuyDoi = new javax.swing.JToggleButton();
        btnDiemUuTien = new javax.swing.JToggleButton();
        btnNguyenVong = new javax.swing.JToggleButton();
        btnXetTuyen = new javax.swing.JToggleButton();
        btnDiemThi = new javax.swing.JToggleButton();
        btnBaoCao = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        btnDangXuat = new javax.swing.JButton();
        mainContent = new javax.swing.JPanel();
        mainContent2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        menuTaskbar.setBackground(new java.awt.Color(255, 255, 255));
        menuTaskbar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuTaskbar.setPreferredSize(new java.awt.Dimension(200, 800));
        menuTaskbar.setLayout(new java.awt.BorderLayout());

        info.setBackground(new java.awt.Color(255, 255, 255));
        info.setPreferredSize(new java.awt.Dimension(136, 70));

        lblTenAdmin.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblTenAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTenAdmin.setText("Lê Nguyễn Hoàng Phát");

        bar.setBackground(new java.awt.Color(0, 0, 0));
        bar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        bar.setPreferredSize(new java.awt.Dimension(1, 1));

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblChucVu.setForeground(new java.awt.Color(153, 153, 153));
        lblChucVu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblChucVu.setText("Quản lý kho");

        javax.swing.GroupLayout infoLayout = new javax.swing.GroupLayout(info);
        info.setLayout(infoLayout);
        infoLayout.setHorizontalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bar, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(lblChucVu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblTenAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        infoLayout.setVerticalGroup(
            infoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTenAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuTaskbar.add(info, java.awt.BorderLayout.NORTH);

        taskBar.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(btnTrangChu);
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnTrangChu.setText("Trang chủ");
        btnTrangChu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnNganh);
        btnNganh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNganh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNganh.setLabel("Ngành");
        btnNganh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNganhActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnToHopMon);
        btnToHopMon.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnToHopMon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnToHopMon.setLabel("Tổ Hợp Môn");
        btnToHopMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToHopMonActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnThiSinh);
        btnThiSinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnThiSinh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThiSinh.setLabel("Thí Sinh");
        btnThiSinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThiSinhActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnBangQuyDoi);
        btnBangQuyDoi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBangQuyDoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBangQuyDoi.setLabel("Bảng Quy Đổi");
        btnBangQuyDoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBangQuyDoiActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDiemUuTien);
        btnDiemUuTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDiemUuTien.setText("Điểm Ưu Tiên");
        btnDiemUuTien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDiemUuTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemUuTienActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnNguyenVong);
        btnNguyenVong.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNguyenVong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNguyenVong.setLabel("Nguyện Vọng");
        btnNguyenVong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNguyenVongActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnXetTuyen);
        btnXetTuyen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnXetTuyen.setText("Xét Tuyển");
        btnXetTuyen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXetTuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXetTuyenActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnDiemThi);
        btnDiemThi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDiemThi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDiemThi.setLabel("Điểm Thi");
        btnDiemThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiemThiActionPerformed(evt);
            }
        });

        buttonGroup1.add(btnBaoCao);
        btnBaoCao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBaoCao.setText("Báo Cáo");
        btnBaoCao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaoCaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout taskBarLayout = new javax.swing.GroupLayout(taskBar);
        taskBar.setLayout(taskBarLayout);
        taskBarLayout.setHorizontalGroup(
            taskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDiemUuTien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnXetTuyen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNguyenVong, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
            .addComponent(btnBangQuyDoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDiemThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThiSinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnToHopMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNganh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBaoCao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        taskBarLayout.setVerticalGroup(
            taskBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTrangChu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNganh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToHopMon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThiSinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiemThi)
                .addGap(5, 5, 5)
                .addComponent(btnBangQuyDoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDiemUuTien)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNguyenVong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXetTuyen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBaoCao)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        menuTaskbar.add(taskBar, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(111, 70));

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnDangXuat)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        menuTaskbar.add(jPanel1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(menuTaskbar, java.awt.BorderLayout.WEST);

        mainContent.setBackground(new java.awt.Color(235, 235, 235));
        mainContent.setPreferredSize(new java.awt.Dimension(1200, 800));
        mainContent.setLayout(new java.awt.BorderLayout());

        mainContent2.setBackground(new java.awt.Color(235, 235, 235));
        mainContent2.setLayout(new javax.swing.OverlayLayout(mainContent2));
        mainContent.add(mainContent2, java.awt.BorderLayout.CENTER);

        getContentPane().add(mainContent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn đăng xuất?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose(); // đóng form hiện tại
//            new Login().setVisible(true); // mở lại form login
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void btnDiemThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemThiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDiemThiActionPerformed

    private void btnXetTuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXetTuyenActionPerformed
        // TODO add your handling code here:
//        this.thongKePanel = new ThongKe();
//        addTaskBar(mainContent2, thongKePanel);
    }//GEN-LAST:event_btnXetTuyenActionPerformed

    private void btnNguyenVongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNguyenVongActionPerformed
        // TODO add your handling code here:
//        this.nhanVienPanel = new NhanVien();
//        addTaskBar(mainContent2, nhanVienPanel);
    }//GEN-LAST:event_btnNguyenVongActionPerformed

    private void btnDiemUuTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiemUuTienActionPerformed
        // TODO add your handling code here:
//        this.nhacungcapPanel = new NhaCungCap();
//        addTaskBar(mainContent2, nhacungcapPanel);
    }//GEN-LAST:event_btnDiemUuTienActionPerformed

    private void btnBangQuyDoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBangQuyDoiActionPerformed
        // TODO add your handling code here:
//        this.khachHangPanel = new KhachHang();
//        addTaskBar(mainContent2, khachHangPanel);
    }//GEN-LAST:event_btnBangQuyDoiActionPerformed

    private void btnThiSinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThiSinhActionPerformed
        // TODO add your handling code here:
//        this.phieuNhapPanel = new PhieuNhap();
//        addTaskBar(mainContent2, phieuNhapPanel);
    }//GEN-LAST:event_btnThiSinhActionPerformed

    private void btnToHopMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToHopMonActionPerformed
        // TODO add your handling code here:
//        this.thuocTinhPanel = new ThuocTinh();
//        addTaskBar(mainContent2, thuocTinhPanel);
    }//GEN-LAST:event_btnToHopMonActionPerformed

    private void btnNganhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNganhActionPerformed
        // TODO add your handling code here:
//        this.sanphamPanel = new SanPham();
//        addTaskBar(mainContent2, sanphamPanel);
    }//GEN-LAST:event_btnNganhActionPerformed

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btnBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaoCaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBaoCaoActionPerformed

    private void addIconTaskbar() {

        btnDangXuat.setText("<html>&nbsp;&nbsp;&nbsp;Đăng xuất</html>");
        btnBangQuyDoi.setText("<html>&nbsp;&nbsp;&nbsp;Bảng Quy Đổi</html>");
        btnDiemUuTien.setText("<html>&nbsp;&nbsp;&nbsp;Điểm Ưu Tiên</html>");
        btnNguyenVong.setText("<html>&nbsp;&nbsp;&nbsp;Nguyện Vọng</html>");
        btnThiSinh.setText("<html>&nbsp;&nbsp;&nbsp;Thí Sinh</html>");
        btnNganh.setText("<html>&nbsp;&nbsp;&nbsp;Ngành</html>");
        btnXetTuyen.setText("<html>&nbsp;&nbsp;&nbsp;Xét Tuyển</html>");
        btnToHopMon.setText("<html>&nbsp;&nbsp;&nbsp;Tổ Hợp Môn</html>");
        btnBaoCao.setText("<html>&nbsp;&nbsp;&nbsp;Tổ Hợp Môn</html>");
        btnTrangChu.setText("<html>&nbsp;&nbsp;&nbsp;Trang chủ</html>");

        // Đặt icon và căn chỉnh biểu tượng sang trái cho mỗi button
        btnTrangChu.setIcon(new FlatSVGIcon("res/icon/home.svg"));
        btnTrangChu.setHorizontalAlignment(SwingConstants.LEFT);

        btnNganh.setIcon(new FlatSVGIcon("res/icon/product.svg"));
        btnNganh.setHorizontalAlignment(SwingConstants.LEFT);

        btnToHopMon.setIcon(new FlatSVGIcon("res/icon/brand.svg"));
        btnToHopMon.setHorizontalAlignment(SwingConstants.LEFT);

        btnThiSinh.setIcon(new FlatSVGIcon("res/icon/import.svg"));
        btnThiSinh.setHorizontalAlignment(SwingConstants.LEFT);

        btnBangQuyDoi.setIcon(new FlatSVGIcon("res/icon/customer.svg"));
        btnBangQuyDoi.setHorizontalAlignment(SwingConstants.LEFT);

        btnDiemUuTien.setIcon(new FlatSVGIcon("res/icon/supplier.svg"));
        btnDiemUuTien.setHorizontalAlignment(SwingConstants.LEFT);

        btnNguyenVong.setIcon(new FlatSVGIcon("res/icon/staff.svg"));
        btnNguyenVong.setHorizontalAlignment(SwingConstants.LEFT);

        btnXetTuyen.setIcon(new FlatSVGIcon("res/icon/statistical.svg"));
        btnXetTuyen.setHorizontalAlignment(SwingConstants.LEFT);

        btnDangXuat.setIcon(new FlatSVGIcon("res/icon/log_out.svg"));
        btnDangXuat.setHorizontalAlignment(SwingConstants.LEFT);
    }

    private void setUT() {
        FlatRobotoFont.install();
        // set font chữ
        FlatLaf.setPreferredFontFamily(FlatRobotoFont.FAMILY); // set size cho font
        FlatLaf.setPreferredLightFontFamily(FlatRobotoFont.FAMILY_LIGHT);
        FlatLaf.setPreferredSemiboldFontFamily(FlatRobotoFont.FAMILY_SEMIBOLD);
        FlatIntelliJLaf.registerCustomDefaultsSource("style");
        FlatIntelliJLaf.setup();

        UIManager.put("Table.showVerticalLines", false); // ẩn đường kể dọc
        UIManager.put("Table.showHorizontalLines", true); // hiện đường kẻ ngang
        UIManager.put("TextComponent.arc", 30);

        UIManager.put("Button.arc", 10); // Thiết lập đường cong là 10 pixel

        UIManager.put("ScrollBar.thumbArc", 999);
        UIManager.put("ScrollBar.thumbInsets", new Insets(2, 2, 2, 2));
        UIManager.put("Button.iconTextGap", 10);

        UIManager.put("PasswordField.showRevealButton", true);

        UIManager.put("Table.selectionBackground", new Color(240, 247, 250));
        UIManager.put("Table.selectionForeground", new Color(0, 0, 0));
        UIManager.put("Table.scrollPaneBorder", new EmptyBorder(0, 0, 0, 0));
        UIManager.put("Table.rowHeight", 40);
        UIManager.put("TabbedPane.selectedBackground", Color.white);
        UIManager.put("TableHeader.height", 40);
        UIManager.put("TableHeader.font", UIManager.getFont("h4.font"));
        UIManager.put("TableHeader.background", new Color(242, 242, 242));
        UIManager.put("TableHeader.separatorColor", new Color(242, 242, 242));
        UIManager.put("TableHeader.bottomSeparatorColor", new Color(242, 242, 242));
        btnTrangChuActionPerformed(null);
    }

//    private void addTaskBar(Container mainContent, JPanel panel) {
//        mainContent.setLayout(new BorderLayout());
//        panel.setSize(mainContent.getSize());
//        mainContent.removeAll();
//        mainContent.add(panel, BorderLayout.CENTER);
//        mainContent.setVisible(true);
//        mainContent.revalidate();
//        mainContent.repaint();
//    }

//    private void phanQuyenTheoVaiTro() {
//        int role = nhanVien.getRoleGroupId();
//
//        if (role == 1) return; // Admin: full quyền
//        if (role == 2) {
//            btnNguyenVong.setVisible(false);
//            btnNhomQuyen.setVisible(false);
//            btnXetTuyen.setVisible(false);
//            btnThiSinh.setVisible(false);
//            btnToHopMon.setVisible(false);
//            btnDiemUuTien.setVisible(false);
//            btnBangQuyDoi.setVisible(false);
//        }
//        if (role == 3) {
//            btnNguyenVong.setVisible(false);
//            btnNhomQuyen.setVisible(false);
//        }
//
//
//    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bar;
    private javax.swing.JToggleButton btnBangQuyDoi;
    private javax.swing.JToggleButton btnBaoCao;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JToggleButton btnDiemThi;
    private javax.swing.JToggleButton btnDiemUuTien;
    private javax.swing.JToggleButton btnNganh;
    private javax.swing.JToggleButton btnNguyenVong;
    private javax.swing.JToggleButton btnThiSinh;
    private javax.swing.JToggleButton btnToHopMon;
    private javax.swing.JToggleButton btnTrangChu;
    private javax.swing.JToggleButton btnXetTuyen;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblTenAdmin;
    private javax.swing.JPanel mainContent;
    private javax.swing.JPanel mainContent2;
    private javax.swing.JPanel menuTaskbar;
    private javax.swing.JPanel taskBar;
    // End of variables declaration//GEN-END:variables

}
